[project]
name = "websearchtool"
version = "0.1.0"
description = "Web Search Agent for AI Integration"
authors = [{ name = "CLoaKY", email = "laysheth1@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.5",
    "pydantic-settings>=2.9.1",
]
